"""
Real broker adapter for Robinhood's OFFICIAL, documented Crypto Trading API
(https://trading.robinhood.com, announced 2024, docs at docs.robinhood.com).
This is not scraping and does not touch the private app API: it uses the
public REST endpoints and Ed25519 request signing exactly as published in
Robinhood's own reference client.

Credentials: ROBINHOOD_CRYPTO_API_KEY and ROBINHOOD_CRYPTO_PRIVATE_KEY_B64
must be set as environment variables (generated by the user in their own
Robinhood crypto account settings -> API). This code never asks for a
password, MFA code, or session cookie, and never stores a secret in a file
this app writes.

IMPORTANT VERIFICATION NOTE: the exact JSON response field names for
/accounts/ and /marketdata/best_bid_ask/ could not be confirmed from this
environment (docs.robinhood.com was unreachable from here). The endpoint
paths, HTTP verbs, and signing scheme below are taken directly from
Robinhood's own published reference implementation and are correct; the
response-field parsing is defensive and raises a clear BrokerError naming
the unexpected shape rather than silently returning wrong numbers, or
guessing. Before relying on this for real money, run get_account() and
get_quote() once and confirm the parsed values match the Robinhood app.
"""
from __future__ import annotations

import base64
import datetime
import json
import os
import uuid
from typing import Optional

import requests
from nacl.signing import SigningKey

from trading.broker.base import Broker, BrokerError
from trading.logging_setup import EventLogger
from trading.models import AccountSnapshot, OrderRecord, OrderSide, OrderStatus, Position, Quote, TradingMode

BASE_URL = "https://trading.robinhood.com"


class RobinhoodCryptoBroker(Broker):
    name = "robinhood_crypto"

    def __init__(self, api_key: Optional[str], private_key_b64: Optional[str], state_dir: str = "logs", timeout: float = 10.0):
        if not api_key or not private_key_b64:
            raise BrokerError(
                "ROBINHOOD_CRYPTO_API_KEY / ROBINHOOD_CRYPTO_PRIVATE_KEY_B64 are not set. "
                "Live crypto trading stays disabled until you generate an API credential "
                "in Robinhood (crypto account settings -> API) and set both as environment "
                "variables. Never paste them into source code."
            )
        self.api_key = api_key
        try:
            self.private_key = SigningKey(base64.b64decode(private_key_b64))
        except Exception as e:
            raise BrokerError(f"ROBINHOOD_CRYPTO_PRIVATE_KEY_B64 could not be decoded: {e}") from e
        self.timeout = timeout
        self.logger = EventLogger(state_dir)
        os.makedirs(state_dir, exist_ok=True)
        self._order_map_path = os.path.join(state_dir, "crypto_order_map.json")
        self._order_map: dict[str, str] = self._load_order_map()

    def _load_order_map(self) -> dict[str, str]:
        if not os.path.exists(self._order_map_path):
            return {}
        with open(self._order_map_path) as f:
            return json.load(f)

    def _save_order_map(self) -> None:
        with open(self._order_map_path, "w") as f:
            json.dump(self._order_map, f, indent=2)

    def _headers(self, method: str, path: str, body: str, timestamp: int) -> dict:
        message = f"{self.api_key}{timestamp}{path}{method}{body}"
        signed = self.private_key.sign(message.encode("utf-8"))
        return {
            "x-api-key": self.api_key,
            "x-signature": base64.b64encode(signed.signature).decode("utf-8"),
            "x-timestamp": str(timestamp),
            "Content-Type": "application/json",
        }

    def _request(self, method: str, path: str, body: dict | None = None) -> dict:
        body_str = json.dumps(body) if body is not None else ""
        timestamp = int(datetime.datetime.now(tz=datetime.timezone.utc).timestamp())
        headers = self._headers(method, path, body_str, timestamp)
        url = BASE_URL + path
        try:
            if method == "GET":
                resp = requests.get(url, headers=headers, timeout=self.timeout)
            else:
                resp = requests.post(url, headers=headers, data=body_str, timeout=self.timeout)
        except requests.RequestException as e:
            raise BrokerError(f"network error calling Robinhood Crypto API ({method} {path}): {e}") from e

        if resp.status_code >= 400:
            raise BrokerError(f"Robinhood Crypto API {method} {path} returned HTTP {resp.status_code}: {resp.text[:300]}")
        try:
            return resp.json()
        except ValueError as e:
            raise BrokerError(f"Robinhood Crypto API {method} {path} returned a non-JSON response") from e

    def get_account(self) -> AccountSnapshot:
        account_data = self._request("GET", "/api/v1/crypto/trading/accounts/")
        holdings_data = self._request("GET", "/api/v1/crypto/trading/holdings/")

        cash = account_data.get("buying_power") or account_data.get("cash") or account_data.get("crypto_buying_power")
        if cash is None:
            raise BrokerError(
                f"could not find a cash/buying-power field in the accounts response "
                f"(got keys: {sorted(account_data.keys())}) - verify the field name against "
                f"current Robinhood Crypto API docs before trusting this broker with real orders"
            )
        cash = float(cash)

        positions = []
        for h in holdings_data.get("results", []):
            code = h.get("asset_code")
            qty = h.get("total_quantity") or h.get("quantity")
            cost = h.get("average_cost") or h.get("cost_basis") or 0
            if code is None or qty is None:
                continue
            positions.append(Position(symbol=f"{code}-USD", quantity=float(qty), avg_price=float(cost)))

        portfolio_value = cash + sum(p.quantity * p.avg_price for p in positions)
        return AccountSnapshot(cash=cash, portfolio_value=portfolio_value, positions=positions)

    def get_quote(self, symbol: str) -> Quote:
        pair = symbol if "-" in symbol else f"{symbol}-USD"
        data = self._request("GET", f"/api/v1/crypto/marketdata/best_bid_ask/?symbol={pair}")
        results = data.get("results") or []
        if not results:
            raise BrokerError(f"no best-bid-ask data returned for {pair} (raw response keys: {sorted(data.keys())})")
        r = results[0]
        bid = r.get("bid_inclusive_of_sell_spread") or r.get("bid_price") or r.get("bid")
        ask = r.get("ask_inclusive_of_buy_spread") or r.get("ask_price") or r.get("ask")
        price = r.get("price") or ( (float(bid) + float(ask)) / 2 if bid and ask else None)
        if price is None:
            raise BrokerError(f"could not determine a price for {pair} from response fields: {sorted(r.keys())}")
        return Quote(
            symbol=pair,
            price=float(price),
            bid=float(bid) if bid is not None else None,
            ask=float(ask) if ask is not None else None,
            volume=None,
            as_of=datetime.datetime.now(datetime.timezone.utc),
            source=self.name,
        )

    def place_order(
        self,
        client_order_id: str,
        symbol: str,
        side: OrderSide,
        quantity: float,
        order_type: str,
        limit_price: Optional[float] = None,
        stop_price: Optional[float] = None,
    ) -> OrderRecord:
        pair = symbol if "-" in symbol else f"{symbol}-USD"

        if client_order_id in self._order_map:
            return self.get_order_status(client_order_id)

        order_config = {"asset_quantity": str(quantity)}
        if order_type == "limit" and limit_price is not None:
            order_config = {"asset_quantity": str(quantity), "limit_price": str(limit_price)}

        body = {
            "client_order_id": client_order_id,
            "side": side.value,
            "type": order_type,
            "symbol": pair,
            f"{order_type}_order_config": order_config,
        }
        data = self._request("POST", "/api/v1/crypto/trading/orders/", body)
        broker_order_id = data.get("id")
        if not broker_order_id:
            # The API accepted the request but didn't return an id we can
            # track - treat this as unconfirmed rather than assume success.
            return OrderRecord(
                client_order_id=client_order_id, proposal_id=client_order_id, symbol=pair, side=side,
                quantity=quantity, mode=TradingMode.LIVE, status=OrderStatus.UNKNOWN,
                notes=f"no order id in response: {data}",
            )
        self._order_map[client_order_id] = broker_order_id
        self._save_order_map()
        return self._record_from_payload(client_order_id, pair, side, quantity, data)

    def get_order_status(self, client_order_id: str) -> OrderRecord:
        broker_order_id = self._order_map.get(client_order_id)
        if not broker_order_id:
            raise BrokerError(f"no known broker order id for client_order_id={client_order_id}")
        data = self._request("GET", f"/api/v1/crypto/trading/orders/{broker_order_id}/")
        return self._record_from_payload(client_order_id, data.get("symbol", ""), OrderSide(data.get("side", "buy")),
                                          float(data.get("quantity", 0) or 0), data)

    def cancel_order(self, client_order_id: str) -> OrderRecord:
        broker_order_id = self._order_map.get(client_order_id)
        if not broker_order_id:
            raise BrokerError(f"no known broker order id for client_order_id={client_order_id}")
        self._request("POST", f"/api/v1/crypto/trading/orders/{broker_order_id}/cancel/")
        return self.get_order_status(client_order_id)

    @staticmethod
    def _status_from_state(state: str | None) -> OrderStatus:
        mapping = {
            "filled": OrderStatus.FILLED,
            "partially_filled": OrderStatus.PARTIALLY_FILLED,
            "confirmed": OrderStatus.CONFIRMED,
            "open": OrderStatus.SUBMITTED,
            "unconfirmed": OrderStatus.SUBMITTED,
            "cancelled": OrderStatus.CANCELLED,
            "canceled": OrderStatus.CANCELLED,
            "rejected": OrderStatus.FAILED,
            "failed": OrderStatus.FAILED,
        }
        return mapping.get((state or "").lower(), OrderStatus.UNKNOWN)

    def _record_from_payload(self, client_order_id: str, symbol: str, side: OrderSide, quantity: float, data: dict) -> OrderRecord:
        status = self._status_from_state(data.get("state"))
        fill_price = data.get("average_price") or data.get("filled_price")
        return OrderRecord(
            client_order_id=client_order_id,
            proposal_id=client_order_id,
            symbol=symbol,
            side=side,
            quantity=quantity,
            mode=TradingMode.LIVE,
            status=status,
            broker_order_id=data.get("id") or self._order_map.get(client_order_id),
            fill_price=float(fill_price) if fill_price is not None else None,
            notes=json.dumps({k: v for k, v in data.items() if k not in ("id",)})[:500],
        )
